---
version: '3'

tasks:
  gen:
    summary: |
      Usage: task gen -- YEAR DAY

      Generate new AoC 'day' files. This includes actual code file in yXXXX directory, as well as benchmark and test files. Lastly, it adds day entry to challenge.go file.
    cmds:
      - scripts/generate.sh {{.CLI_ARGS}}

  run:
    summary: |
      Usage: task run -- YEAR DAY PART

      Run selected challenge, based on provided year, day and part.
    cmds:
      - go run . {{.CLI_ARGS}}

  new1:
    summary: |
      Usage: task new1

      Run part one of the newest existing entry on challenge list.
    cmds:
      - go run . {{.DAY}} 01
    vars:
      DAY:
        sh: >
          cat challenge.go |
          tail -2 |
          head -1 |
          tr -d '[:space:]' |
          cut -d '"' -f 2 |
          tr '/' ' '

  new2:
    summary: |
      Usage: task new2

      Run part two of the newest existing entry on challenge list.
    cmds:
      - go run . {{.DAY}} 02
    vars:
      DAY:
        sh: >
          cat challenge.go |
          tail -2 |
          head -1 |
          tr -d '[:space:]' |
          cut -d '"' -f 2 |
          tr '/' ' '

  bench:
    summary: |
      Usage: task bench -- YEAR DAY [PART]

      Run benchmarks for selected day, optionally specifying part.
    cmds:
      - scripts/bench.sh {{.CLI_ARGS}}
      # - defer: rm -rf ./benchmark/*/input

  bnew1:
    summary: |
      Usage: task bnew1

      Run benchmarks for the part one of the newest existing entry on challenge list, and save it to a file.
    cmds:
      - scripts/bench.sh {{.DAY}} 01
      - defer: rm -rf ./benchmark/*/input
    vars:
      DAY:
        sh: >
          cat challenge.go |
          tail -2 |
          head -1 |
          tr -d '[:space:]' |
          cut -d '"' -f 2 |
          tr '/' ' '

  bnew2:
    summary: |
      Usage: task bnew2

      Run benchmarks for the part two of the newest existing entry on challenge list, and save it to a file.
    cmds:
      - scripts/bench.sh {{.DAY}} 02
      # - defer: rm -rf ./benchmark/*/input
    vars:
      DAY:
        sh: >
          cat challenge.go |
          tail -2 |
          head -1 |
          tr -d '[:space:]' |
          cut -d '"' -f 2 |
          tr '/' ' '

  benchAll:
    summary: |
      Usage: task benchAll

      Run all benchmarks, for all days, for all years.
    cmds:
      - go test -bench . ./benchmark/...
      - defer: rm -rf ./benchmark/*/input

  test:
    summary: |
      Usage: task test -- YEAR DAY [PART]

      Run tests for selected day, optionally specifying part.
    cmds:
      - scripts/test.sh {{.CLI_ARGS}}

  tnew1:
    summary: |
      Usage: task tnew1

      Run tests for the part one of the newest existing entry on challenge list.
    cmds:
      - scripts/test.sh {{.DAY}} 01
    vars:
      DAY:
        sh: >
          cat challenge.go |
          tail -2 |
          head -1 |
          tr -d '[:space:]' |
          cut -d '"' -f 2 |
          tr '/' ' '

  tnew2:
    summary: |
      Usage: task tnew2

      Run tests for the part two of the newest existing entry on challenge list.
    cmds:
      - scripts/test.sh {{.DAY}} 02
    vars:
      DAY:
        sh: >
          cat challenge.go |
          tail -2 |
          head -1 |
          tr -d '[:space:]' |
          cut -d '"' -f 2 |
          tr '/' ' '

  testAll:
    summary: |
      Usage: task testAll

      Run all tests, for all days, for all years.
    cmds:
      - go test -run . ./test/...

  default:
    summary: |
      Usage: task

      Show task list.
    cmds:
      - task --list-all
...
