---
version: '3'

tasks:
  gen:
    cmds:
      - scripts/generate.sh {{.CLI_ARGS}}

  run:
    cmds:
      - go run . {{.CLI_ARGS}}

  new1:
    cmds:
      - go run . {{.DAY}} 01
    vars:
      DAY:
        sh: >
          cat challenge.go |
          tail -2 |
          head -1 |
          tr -d '[:space:]' |
          cut -d '"' -f 2 |
          tr '/' ' '

  new2:
    cmds:
      - go run . {{.DAY}} 02
    vars:
      DAY:
        sh: >
          cat challenge.go |
          tail -2 |
          head -1 |
          tr -d '[:space:]' |
          cut -d '"' -f 2 |
          tr '/' ' '

  bench:
    cmds:
      - scripts/bench.sh {{.CLI_ARGS}}

  bnew1:
    cmds:
      - scripts/bench.sh {{.DAY}} 01
    vars:
      DAY:
        sh: >
          cat challenge.go |
          tail -2 |
          head -1 |
          tr -d '[:space:]' |
          cut -d '"' -f 2 |
          tr '/' ' '

  bnew2:
    cmds:
      - scripts/bench.sh {{.DAY}} 02
    vars:
      DAY:
        sh: >
          cat challenge.go |
          tail -2 |
          head -1 |
          tr -d '[:space:]' |
          cut -d '"' -f 2 |
          tr '/' ' '

  benchAll:
    cmds:
      - go test -bench . ./benchmark/...
      - defer: rm -rf ./benchmark/*/input

  test:
    cmds:
      - echo

  tnew1:
    cmds:
      - echo

  tnew2:
    cmds:
      - echo

  testAll:
    cmds:
      - echo

  default:
    cmds:
      - task --list-all
...
